#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# package-vm.sh — Packer-based VM image builder for AnonReq appliance.
#
# Builds bootable VM images (QEMU QCOW2 + AWS AMI) containing Docker Engine,
# Docker Compose, and the AnonReq gateway services managed by systemd.
#
# Prerequisites:
#   - Packer >= 1.9 (https://packer.io/downloads)
#   - QEMU (for qcow2 build: `brew install qemu` or `apt install qemu-system-x86`)
#   - AWS CLI configured (for AMI build)
#   - Docker images built locally (`docker compose build`)
#
# Usage:
#   ./scripts/package-vm.sh [--builder qemu|aws|all] [--version X.Y.Z]
#
# Examples:
#   ./scripts/package-vm.sh --builder qemu --version 1.0.0
#   ./scripts/package-vm.sh --builder aws --version 1.0.0
#   ./scripts/package-vm.sh --builder all --version 1.0.0
#
# Outputs:
#   - build/anonreq-{version}.qcow2 (QEMU builder)
#   - build/anonreq-{version}.ami (marker file, AMI built via Packer + AWS)
#
# Per T-17-03-04:
#   - Validates checksums of all downloaded packages
#   - Docker images built from source before packaging
#   - Script checks GPG signatures of Docker packages
# ---------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
BUILDER="${1:-qemu}"
VERSION="${2:-0.1.0}"
OUTPUT_DIR="${PROJECT_DIR}/build"

# ---------------------------------------------------------------------------
# Color output helpers
# ---------------------------------------------------------------------------
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
preflight_checks() {
    info "Running pre-flight checks..."

    # Check Packer
    if ! command -v packer &>/dev/null; then
        error "Packer not found. Install from https://packer.io/downloads"
        exit 1
    fi

    PACKER_VER=$(packer version | head -1 | grep -oP '\d+\.\d+' | head -1)
    info "Packer version: $(packer version | head -1)"

    # Check Docker images exist
    if [ ! -f "${PROJECT_DIR}/docker-compose.yml" ]; then
        error "docker-compose.yml not found in project root"
        exit 1
    fi

    # Verify Dockerfile exists
    if [ ! -f "${PROJECT_DIR}/Dockerfile" ]; then
        error "Dockerfile not found in project root"
        exit 1
    fi

    # Build Docker images if needed
    info "Building Docker images..."
    (cd "$PROJECT_DIR" && docker compose build --quiet 2>/dev/null || docker compose build)

    # Check chosen builder
    case "$BUILDER" in
        qemu)
            if ! command -v qemu-system-x86_64 &>/dev/null; then
                warn "QEMU not found. Install with: brew install qemu"
            fi
            ;;
        aws)
            if ! command -v aws &>/dev/null; then
                error "AWS CLI not found. Install from https://aws.amazon.com/cli/"
                exit 1
            fi
            ;;
        all)
            if ! command -v qemu-system-x86_64 &>/dev/null; then
                warn "QEMU not found — QCOW2 build may fail"
            fi
            if ! command -v aws &>/dev/null; then
                error "AWS CLI not found"
                exit 1
            fi
            ;;
        *)
            error "Unknown builder: $BUILDER (use: qemu, aws, all)"
            exit 1
            ;;
    esac

    info "All pre-flight checks passed."
}

# ---------------------------------------------------------------------------
# Generate Packer HCL configuration
# ---------------------------------------------------------------------------
generate_packer_config() {
    local builder_type="$1"
    local output_path="${OUTPUT_DIR}/packer_${builder_type}.pkr.hcl"

    mkdir -p "$OUTPUT_DIR"

    # Generate builder-specific Packer config
    cat > "$output_path" << PACKER_EOF
# AnonReq Appliance VM Image — Packer configuration
# Generated by package-vm.sh for ${builder_type} builder
# Version: ${VERSION}

variable "version" {
  type    = string
  default = "${VERSION}"
}

variable "ssh_username" {
  type    = string
  default = "ubuntu"
}

locals {
  anonreq_version = var.version
  compose_dir     = "/opt/anonreq"
  systemd_dir     = "/etc/systemd/system"
}

source "amazon-ebs" "anonreq" {
  ami_name      = "anonreq-${VERSION}-{{timestamp}}"
  instance_type = "t3.medium"
  region        = "us-east-1"
  source_ami_filter {
    filters = {
      name                = "ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*"
      root-device-type    = "ebs"
      virtualization-type = "hvm"
    }
    most_recent = true
    owners      = ["099720109477"]  # Canonical
  }
  ssh_username = var.ssh_username
  tags = {
    Name        = "anonreq-${VERSION}"
    Version     = "${VERSION}"
    Service     = "AnonReq Gateway"
  }
}

source "qemu" "anonreq" {
  iso_url           = "https://releases.ubuntu.com/noble/ubuntu-24.04-live-server-arm64.iso"
  iso_checksum      = "file:https://releases.ubuntu.com/noble/SHA256SUMS"
  output_directory  = "${OUTPUT_DIR}/anonreq-${VERSION}-qcow2"
  disk_size         = "20G"
  format            = "qcow2"
  ssh_username      = var.ssh_username
  ssh_timeout       = "20m"
  boot_wait         = "10s"
  memory            = 2048
  cpus              = 2
}

build {
  sources = ["source.${builder_type == "qemu" ? "qemu" : "amazon-ebs"}.anonreq"]

  provisioner "shell" {
    inline = [
      # Install Docker Engine
      "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker.gpg",
      "echo 'deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable' | sudo tee /etc/apt/sources.list.d/docker.list",
      "sudo apt-get update -qq",
      "sudo apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin python3.12 python3.12-venv ufw",
      "sudo systemctl enable docker",
    ]
  }

  provisioner "file" {
    source      = "${PROJECT_DIR}/docker-compose.yml"
    destination = "/tmp/docker-compose.yml"
  }

  provisioner "file" {
    source      = "${PROJECT_DIR}/systemd/anonreq-agent.service"
    destination = "/tmp/anonreq-agent.service"
  }

  provisioner "file" {
    source      = "${PROJECT_DIR}/.env.example"
    destination = "/tmp/anonreq.env"
  }

  provisioner "shell" {
    inline = [
      # Set up AnonReq directory structure
      "sudo mkdir -p /opt/anonreq /etc/anonreq /var/lib/anonreq /var/log/anonreq",
      "sudo mv /tmp/docker-compose.yml /opt/anonreq/docker-compose.yml",
      "sudo mv /tmp/anonreq-agent.service /etc/systemd/system/anonreq-agent.service",
      "sudo mv /tmp/anonreq.env /etc/anonreq/config.env",

      # Create anonreq user
      "sudo useradd --system --no-create-home --shell /usr/sbin/nologin anonreq || true",
      "sudo usermod -aG docker anonreq",
      "sudo chown -R anonreq:anonreq /opt/anonreq /etc/anonreq /var/lib/anonreq /var/log/anonreq",

      # Configure firewall
      "sudo ufw allow 8080/tcp comment 'AnonReq HTTP proxy'",
      "sudo ufw allow 443/tcp comment 'AnonReq HTTPS proxy'",
      "sudo ufw allow 8443/tcp comment 'AnonReq management'",
      "sudo ufw --force enable",

      # Enable systemd services
      "sudo systemctl enable anonreq-agent.service",
      "sudo systemctl enable docker",

      # Set up log rotation
      "cat > /tmp/anonreq-logrotate << 'EOF'",
      "/var/log/anonreq/*.log {",
      "  daily",
      "  rotate 30",
      "  compress",
      "  delaycompress",
      "  missingok",
      "  notifempty",
      "  copytruncate",
      "}",
      "EOF",
      "sudo mv /tmp/anonreq-logrotate /etc/logrotate.d/anonreq",
      "sudo chmod 644 /etc/logrotate.d/anonreq",
    ]
  }

  post-processor "manifest" {
    output     = "${OUTPUT_DIR}/anonreq-${VERSION}.${builder_type}.manifest.json"
    strip_path = true
  }
}
PACKER_EOF

    echo "$output_path"
}

# ---------------------------------------------------------------------------
# Run Packer build
# ---------------------------------------------------------------------------
run_packer_build() {
    local builder_type="$1"
    local config_file
    config_file=$(generate_packer_config "$builder_type")

    info "Starting Packer build for ${builder_type} (version ${VERSION})..."
    info "Config: ${config_file}"

    # Validate Packer configuration
    packer validate "$config_file"

    # Run Packer build
    packer build \
        -var "version=${VERSION}" \
        "$config_file"

    # Create output marker
    case "$builder_type" in
        qemu)
            touch "${OUTPUT_DIR}/anonreq-${VERSION}.qcow2.marker"
            info "QCOW2 image built: ${OUTPUT_DIR}/anonreq-${VERSION}.qcow2"
            ;;
        aws)
            echo "anonreq-${VERSION}" > "${OUTPUT_DIR}/anonreq-${VERSION}.ami"
            info "AMI built: anonreq-${VERSION} (see AWS console)"
            ;;
    esac
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    echo "=============================================="
    echo "  AnonReq VM Image Packager v${VERSION}"
    echo "  Builder: ${BUILDER}"
    echo "=============================================="
    echo ""

    preflight_checks

    case "$BUILDER" in
        qemu)
            run_packer_build "qemu"
            ;;
        aws)
            run_packer_build "amazon-ebs"
            ;;
        all)
            run_packer_build "qemu"
            run_packer_build "amazon-ebs"
            ;;
    esac

    echo ""
    info "Build complete! Output in: ${OUTPUT_DIR}"
}

main "$@"
